apiVersion: apps/v1
kind: Deployment

metadata:
  name: lung-cancer-app
  namespace: lung-cancer

spec:

  replicas: 4

  selector:
    matchLabels:
      app: lung-cancer-app

  template:

    metadata:
      labels:
        app: lung-cancer-app

    spec:

      containers:

        - name: lung-cancer-app

          image: 821656895219.dkr.ecr.ap-south-1.amazonaws.com/lung-cancer-mlops:logistic_regression-a8e330b

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          resources:

            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
