apiVersion: v1
kind: Service

metadata:
  name: lung-cancer-service
  namespace: lung-cancer

spec:

  type: LoadBalancer

  selector:
    app: lung-cancer-app

  ports:

    - name: http

      protocol: TCP

      port: 80

      targetPort: 8000
